In [298]:
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objs as go
import sympy as sp
from IPython.display import HTML

In [299]:
# Helpers for visualisation of matrices
def matrixToLatex(matrix):
    return sp.latex(sp.Matrix(matrix))

def displayMatrix(m):
    display(HTML(dontScroll(r'${} $'.format(matrixToLatex(m)))))
    print('\n')

def dontScroll(html):
    return r'<div style="overflow-x:auto; overflow-y:hidden; display:inline-block;">{}</div>'.format(html)

def displayOperationMatrix(A, B, C, operator):
    display(HTML(dontScroll(r'${A} {operator} {B} = {C} $'.format(A = matrixToLatex(A), B = matrixToLatex(B), C = matrixToLatex(C), operator=operator))))
    print('\n')


# Matrixes

## Matrix

In [300]:
matrix_2x2 = np.array([
    [1, 2],
    [3, 4],
])
displayMatrix(matrix_2x2)

In [301]:
matrix_2x3 = np.array([
    [1, 2, 3],
    [4, 5, 6],
])
displayMatrix(matrix_2x3)

In [302]:
matrix_3x2 = np.array([
    [1, 2],
    [3, 4],
    [5, 6]
])
displayMatrix(matrix_3x2)

In [303]:
matrix_3x3 = np.array([
    [1, 2, 3],
    [1, 2, 6],
    [1, 2, 9]
])
displayMatrix(matrix_3x3)

### Zeros matrix

In [304]:
zeros_matrix = np.zeros((3, 3))
displayMatrix(zeros_matrix)

### Ones matrix

In [305]:
ones_matrix = np.ones((3, 3))
displayMatrix(ones_matrix)

### Identity matrix

In [306]:
identity_matrix = np.eye(3)
displayMatrix(identity_matrix)

### Random matrix

In [307]:
random_matrix = np.random.rand(3, 3)
displayMatrix(random_matrix)

# Operations

In [308]:
A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9],
])

B = np.array([
    [1, 1, 1],
    [2, 2, 2],
    [3, 3, 3],
])


### Addition

In [309]:
C = A + B
displayOperationMatrix(A, B, C, '+')
C = B + A
displayOperationMatrix(B, A, C, '+')
C = A + zeros_matrix
displayOperationMatrix(A, zeros_matrix, C, '+')
C = A + ones_matrix
displayOperationMatrix(A, ones_matrix, C, '+')
C = A + identity_matrix
displayOperationMatrix(A, identity_matrix, C, '+')
C = A + random_matrix
displayOperationMatrix(A, random_matrix, C, '+')

### Subtraction

In [310]:
C = A - B
displayOperationMatrix(A, B, C, '-')
C = B - A
displayOperationMatrix(B, A, C, '-')
C = A - zeros_matrix
displayOperationMatrix(A, zeros_matrix, C, '-')
C = A - ones_matrix
displayOperationMatrix(A, ones_matrix, C, '-')
C = A - identity_matrix
displayOperationMatrix(A, identity_matrix, C, '-')
C = A - random_matrix
displayOperationMatrix(A, random_matrix, C, '-')

#### Note

matrix_2x2 - matrix_3x3 is not possible

### Scalar Multiplication

In [311]:
scalar = 2
C = scalar * A
print("Scalar multiplication:\n", C)

Scalar multiplication:
 [[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


### Matrix multiplication (dot product) 

only for 2 dimensional arrays

In [312]:
C = np.dot(A, B)
displayOperationMatrix(A, B, C, '.')
C = np.dot(A, B)
displayOperationMatrix(A, B, C, '.')
C = np.dot(B, A)
displayOperationMatrix(B, A, C, '.')
C = np.dot(A, zeros_matrix)
displayOperationMatrix(A, zeros_matrix, C, '.')
C = np.dot(A, ones_matrix)
displayOperationMatrix(A, ones_matrix, C, '.')
C = np.dot(A, identity_matrix)
displayOperationMatrix(A, identity_matrix, C, '.')
C = np.dot(A, random_matrix)
displayOperationMatrix(A, random_matrix, C, '.')

### Matrix multiplication - matmul

This short syntax using the @ operator is equivalent to using numpy.matmul or numpy.dot for 2-dimensional arrays. Keep in mind that the @ operator follows the rules of matrix multiplication, and it does not perform element-wise multiplication or broadcasting.

In [313]:
C = A @ B
displayOperationMatrix(A, B, C, '@')
C = B @ A
displayOperationMatrix(B, A, C, '@')
C = A @ zeros_matrix
displayOperationMatrix(A, zeros_matrix, C, '@')
C = A @ ones_matrix
displayOperationMatrix(A, ones_matrix, C, '@')
C = A @ identity_matrix
displayOperationMatrix(A, identity_matrix, C, '@')
C = A @ random_matrix
displayOperationMatrix(A, random_matrix, C, '@')

### Element-wise multiplication (Hadamard product):

In [314]:
C = A * B
displayOperationMatrix(A, B, C, '*')
C = B * A
displayOperationMatrix(B, A, C, '*')
C = A * zeros_matrix
displayOperationMatrix(A, zeros_matrix, C, '*')
C = A * ones_matrix
displayOperationMatrix(A, ones_matrix, C, '*')
C = A * identity_matrix
displayOperationMatrix(A, identity_matrix, C, '*')
C = A * random_matrix
displayOperationMatrix(A, random_matrix, C, '*')

### Transpose

In [315]:
C = A.T
displayMatrix(C)

### Inverse

In [316]:
C = np.linalg.inv(A)
displayMatrix(C)

### Determinant

In [317]:
det = np.linalg.det(A)
print("Matrix determinant:\n", det)

Matrix determinant:
 -9.51619735392994e-16


### Rank

In [318]:
rank = np.linalg.matrix_rank(A)
print("Matrix rank:\n", rank)

Matrix rank:
 2


### Eigenvalues and eigenvectors

In [319]:
eigenvalues, eigenvectors = np.linalg.eig(A)
displayMatrix([eigenvalues])
displayMatrix(eigenvectors)

In [320]:
### Dimensions test

In [321]:
print('\n ADDITION TEST')

try:
    C = A + matrix_2x2
    displayOperationMatrix(A, matrix_2x2, C, '+')
except:
    print("matrix_3x3 + matrix_2x2 is not possible operation")
    
try:
    C = A + matrix_2x3
    displayOperationMatrix(A, matrix_2x3, C, '+')
except:
    print("matrix_3x3 + matrix_2x3 is not possible operation")

try:
    C = A + matrix_3x2
    displayOperationMatrix(A, matrix_3x2, C, '+')
except:
    print("matrix_3x3 + matrix_3x2 is not possible operation")

print('\n SUBTRACTION TEST')

try:
    C = A - matrix_2x2
    displayOperationMatrix(A, matrix_2x2, C, '-')
except:
    print("matrix_3x3 - matrix_2x2 is not possible operation")
    
try:
    C = A - matrix_2x3
    displayOperationMatrix(A, matrix_2x3, C, '-')
except:
    print("matrix_3x3 - matrix_2x3 is not possible operation")

try:
    C = A - matrix_3x2
    displayOperationMatrix(A, matrix_3x2, C, '-')
except:
    print("matrix_3x3 - matrix_3x2 is not possible operation")

print('\n MATMUL TEST')

try:
    C = A @ matrix_2x2
    displayOperationMatrix(A, matrix_2x2, C, '@')
except:
    print("matrix_3x3 @ matrix_2x2 is not possible operation")
    
try:
    C = A @ matrix_2x3
    displayOperationMatrix(A, matrix_2x3, C, '@')
except:
    print("matrix_3x3 @ matrix_2x3 is not possible operation")

try:
    C = A @ matrix_3x2
    displayOperationMatrix(A, matrix_3x2, C, '@')
except:
    print("matrix_3x3 @ matrix_3x2 is not possible operation")
    
print('\n Element-wise multiplication (Hadamard product)')

try:
    C = A * matrix_2x2
    displayOperationMatrix(A, matrix_2x2, C, '*')
except:
    print("matrix_3x3 * matrix_2x2 is not possible operation")
    
try:
    C = A * matrix_2x3
    displayOperationMatrix(A, matrix_2x3, C, '*')
except:
    print("matrix_3x3 * matrix_2x3 is not possible operation")

try:
    C = A * matrix_3x2
    displayOperationMatrix(A, matrix_3x2, C, '*')
except:
    print("matrix_3x3 * matrix_3x2 is not possible operation")


 ADDITION TEST
matrix_3x3 + matrix_2x2 is not possible operation
matrix_3x3 + matrix_2x3 is not possible operation
matrix_3x3 + matrix_3x2 is not possible operation

 SUBTRACTION TEST
matrix_3x3 - matrix_2x2 is not possible operation
matrix_3x3 - matrix_2x3 is not possible operation
matrix_3x3 - matrix_3x2 is not possible operation

 MATMUL TEST
matrix_3x3 @ matrix_2x2 is not possible operation
matrix_3x3 @ matrix_2x3 is not possible operation





 Element-wise multiplication (Hadamard product)
matrix_3x3 * matrix_2x2 is not possible operation
matrix_3x3 * matrix_2x3 is not possible operation
matrix_3x3 * matrix_3x2 is not possible operation
